# Generated by Django 5.0.1 on 2024-02-09 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autenticacao', '0003_pessoa_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pessoa',
            name='cargo',
        ),
        migrations.AddField(
            model_name='pessoa',
            name='cargo',
            field=models.ManyToManyField(to='autenticacao.cargo'),
        ),
    ]
